### PR TITLE
Find libmagic installed with brew on OSX in non-standard prefix

### PR DESCRIPTION
**Pull request by lucafavatella**
I - and probably other users of brew - use a custom prefix.  Teach
python-magic to ask brew what the prefix is and look there as well.

I tried the approach described in the references below but it did not
work for me:
  https://stackoverflow.com/questions/22483824/how-to-get-python-to-load-right-library-a-dylib-not-so-3-on-osx/22486117#22486117
  http://notmuchmail.org/pipermail/notmuch/2013/015424.html
  http://git.notmuchmail.org/git/notmuch/blobdiff/b60fb3309cca82dd2789f45ad9cccaacdc291089..acb079e35726cc421b6a314ab4f26d5eb92feaf1:/bindings/python/notmuch/globals.py

### CODE REVIEW

**Comment by raimue** [comment]
macOS is using Mach-O and dyld and has no env variable such as `LD_LIBRARY_PATH`. In Mach-O, the full path to a library is hardcoded in binaries. Although `DYLD_LIBRARY_PATH` exists, the semantic is different and may override system libraries as a side effect, which is usually not intended. The closest thing to achieve this would be to set `DYLD_FALLBACK_LIBRARY_PATH`.

For MacPorts we now even [hardcode the path](https://trac.macports.org/changeset/150008) to `libmagic.dylib` provided by the dependency in the same custom prefix.

**Comment by rickard-von-essen** [comment]
This seems to work for me :+1:

**Comment by lucafavatella** [comment]
Looking at this pull request after 2 years, it still makes sense to me.

What would look better to me - but is outside the scope of this pull request - is moving away from custom definition of paths of dynamic libraries where to look for and rather rely on some standard utility if any e.g. pkg-config (but I am not sure pkg-config is guaranteed to be installed).

**Comment by lucafavatella** [comment]
I am closing this PR and deleting my fork. I understand the closed PR shall have the copy of the code in case anyone needs it.

**Pull request closed without merging**
