### PR TITLE
Redo compat

### PR DESCRIPTION
**Pull request by SchoolGuy**
After I got in touch with @cbiedl, I volunteered to fix the tests and make this Library Python 3 because Python 2 is dead.

@ahupp What are your desires in regard of the compat layer? I need this to work for my project and this is a blocker for the next release. Thus I am very interested to help! :)

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@ahupp Be aware that we need to switch to travis-ci.com to fix the tests fully. If you don't want to do this, I would also port the CI to Github Actions if that is more desired for you. Using Gitlab is not possible due to the fact that their CI doesn't support PRs from GH yet. Other providers I sadly can't help with for now.

**Comment by SchoolGuy** [comment]
When I run this locally, CentOS 7 Tests are failing due to a bad filedescriptor...

**Comment by SchoolGuy** [comment]
@cbiedl Do I forget to fix anything we talked about? (Or if you are feeling generous would you even do a formal review?)

**Comment by ahupp** [comment]
@SchoolGuy @cbiedl thank you so much for getting this over the finish line, and I apologize for putting it off so long.  I'll put out a new release today (taking out the python2 removal), and then a new major version bump with the python2 removal.

**Pull request merged**
